#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely.
# Displays I am invincible!!! when receiving a SIGTERM signal
s="To infinity and beyond"
j="I am invincible!!!"
while true
do
    echo "$s"
    sleep 2
    trap 'echo "$j"' SIGTERM
done
