#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely.
# Displays I am invincible!!! when receiving a SIGTERM signal
s="To infinity and beyond"
while true
do
    echo "$s"
    sleep 2
    trap 'echo "I am invincible"' SIGTERM
done
